### ISSUE TITLE
Custom CF resource timeout

### ISSUE THREAD

**Issue by halas-cz** [aws-samples/aws-iot-twinmaker-samples#159]
From CF console: CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [d1a27269-63ff-46de-acdc-d544ce66bdf5]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

Resource creation times out after 60 mins.

Dump from CW below:
File "/opt/python/cv2/__init__.py", line 153, in bootstrap
--
native_module = importlib.import_module("cv2")
File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
START RequestId: deb0d402-caac-4fca-8f78-1df619333953 Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] Runtime.ImportModuleError: Unable to import module 'data_resource_handler': numpy.core.multiarray failed to importTraceback (most recent call last):
END RequestId: deb0d402-caac-4fca-8f78-1df619333953

**Comment by bucketdeveloper** [comment]
The fix is to update the version of opencv. 

Update /src/libs/opencv_utils/requirements.txt to reflect the following: 

**opencv-python-headless==4.10.0.84**
requests==2.31.0
urllib3<2
