### ISSUE TITLE
Tables are not being created for TimestreamTelemetryCdkLambdasStack database

### ISSUE THREAD

**Issue by jasonyi89** [aws-samples/aws-iot-twinmaker-samples#16]
/AWS/aws-iot-twinmaker-samples/src/workspaces/cookiefactory> python3 -m setup_content --telemetry-stack-name $TIMESTREAM_TELEMETRY_STACK_NAME --workspace-id $WORKSPACE_ID --region-name $AWS_DEFAULT_REGION  --import-all
Traceback (most recent call last):
  File "c:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\opt\AWS\aws-iot-twinmaker-samples\src\workspaces\cookiefactory\setup_content\__main__.py", line 179, in <module>
    main()
  File "c:\opt\AWS\aws-iot-twinmaker-samples\src\workspaces\cookiefactory\setup_content\__main__.py", line 89, in main
    telemetry = timestream_libs.TimestreamTelemetryImporter(
  File "c:\opt\AWS\aws-iot-twinmaker-samples\src\workspaces\cookiefactory\setup_content\../../../modules\timestream_telemetry\lib\TimestreamTelemetryUtils.py", line 22, in __init__
    cfn_stack_description = cfn_client.describe_stacks(StackName=stack_name)
  File "C:\Users\SRJ\AppData\Roaming\Python\Python310\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\SRJ\AppData\Roaming\Python\Python310\site-packages\botocore\client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id CookieFactoryTelemetry does not exist
using following timestamp for data ingestion: 2022-02-03 03:19:28 UTC (1643858368758ms from epoch)

**Comment by hanamz** [comment]
Hi, thanks for reaching out. Looking at the error message which is complaining that CookieFactoryTelemetry stack does not exist. There could be two reasons for it:
1. You didn't deploy the CookieFactoryTelemetry stack. Please check if such stack exists in CloudFormation. If it is deployed successfully, then you should be able to see a stack with name CookieFactoryTelemetry in CloudFormation console. If not, please follow instruction **Deploy an Instance of the Timestream Telemetry module.** in [link](https://github.com/aws-samples/aws-iot-twinmaker-samples)
2. You deployed the CookieFactoryTelemetry Stack with a different name. If you changed the stack name to a customized name, please change the env variable $TIMESTREAM_TELEMETRY_STACK_NAME to your customized name.

**Comment by johnnyw-aws** [comment]
Hi @jasonyi89, please let us know if @hanamz's suggestions didn't resolve the issue. Otherwise we'll close this issue soon, thanks!

**Comment by jasonyi89** [comment]
I wasn't able to figure out the problem trying to install in Windows 10.  However installing and running from AWS Cloud 9 worked.  Thank you.
