### ISSUE TITLE
issue in this, some recomendation 

### ISSUE THREAD

**Issue by IsmaRojo** [aws-samples/aws-iot-twinmaker-samples#31]
Deploy an Instance of the Timestream Telemetry module.

failed to register layer: Error processing tar file(exit status 1): write /usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/rt.jar: no space left on device

/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/@aws-cdk/core/lib/bundling.ts:276
    throw new Error(`${prog} exited with status ${proc.status}`);
          ^
Error: docker exited with status 1
    at dockerExec (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/@aws-cdk/core/lib/bundling.ts:276:11)
    at Function.fromBuild (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/@aws-cdk/core/lib/bundling.ts:159:5)
    at Object.bundle (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/@aws-cdk/aws-lambda-python/lib/bundling.ts:106:33)
    at new PythonLayerVersion (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/@aws-cdk/aws-lambda-python/lib/layer.ts:43:13)
    at new TimestreamTelemetryCdkLambdasStack (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/lib/timestream_telemetry_lambdas-stack.ts:45:11)
    at Object.<anonymous> (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/bin/timestream_telemetry_cdk_lambdas.ts:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ec2-user/environment/aws-iot-twinmaker-samples/src/modules/timestream_telemetry/cdk/node_modules/ts-node/src/index.ts:1059:12)

**Comment by johnnyw-aws** [comment]
Hi @IsmaRojo, from the error `no space left on device` it looks like you may need to increase the disk space for your EC2 instance or remove unnecessary files. Can you try the steps in https://github.com/aws-samples/aws-iot-twinmaker-samples/blob/main/CLOUD9_SETUP.md under "Expand volume size" ?

**Comment by johnnyw-aws** [comment]
Hi @IsmaRojo, please let us know if the above suggestions didn't resolve the issue. Otherwise we'll close this issue soon, thanks!
